# Generated by Django 4.1.7 on 2023-02-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormWhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subitems', models.ManyToManyField(to='product.forwhomcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_items', models.ManyToManyField(related_name='form_whom_list', to='product.formwhom')),
            ],
        ),
        migrations.RenameField(
            model_name='technologycategory',
            old_name='title',
            new_name='title_type',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='for_whom',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddField(
            model_name='subitems',
            name='title_type',
            field=models.ManyToManyField(to='product.technologycategory'),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='sub_items',
            field=models.ManyToManyField(to='product.subitems'),
        ),
    ]
