# Generated by Django 4.1.7 on 2023-02-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='place_category',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='status_category',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ManyToManyField(related_name='product_image', to='product.mediabanner'),
        ),
        migrations.AddField(
            model_name='banner',
            name='place_category',
            field=models.ManyToManyField(related_name='banner_place_category', to='product.placecategory'),
        ),
        migrations.AddField(
            model_name='banner',
            name='status_category',
            field=models.ManyToManyField(related_name='banner_status_category', to='product.status'),
        ),
    ]
