# Generated by Django 4.1.7 on 2023-02-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_formwhom_subitems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subitems',
            name='title_type',
        ),
        migrations.AddField(
            model_name='subitems',
            name='title_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.technologycategory'),
        ),
    ]
