# Generated by Django 4.1.7 on 2023-02-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_subitems_title_type_subitems_title_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitems',
            name='sub_items',
            field=models.ManyToManyField(related_name='form_whom_list', to='product.forwhomcategory'),
        ),
        migrations.DeleteModel(
            name='FormWhom',
        ),
    ]
