# Generated by Django 4.1.7 on 2023-02-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_banner_image_remove_banner_place_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ManyToManyField(related_name='product_image', to='product.mediabanner'),
        ),
    ]
