# Generated by Django 4.1.7 on 2023-02-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_subitems_sub_items_delete_formwhom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subItem', models.CharField(max_length=55)),
            ],
        ),
        migrations.RenameField(
            model_name='catalogcategory',
            old_name='sub_items',
            new_name='subItems',
        ),
        migrations.RenameField(
            model_name='subitems',
            old_name='sub_items',
            new_name='subItems',
        ),
        migrations.RenameField(
            model_name='subitems',
            old_name='title_type',
            new_name='titleType',
        ),
        migrations.RenameField(
            model_name='technologycategory',
            old_name='title_type',
            new_name='titleType',
        ),
        migrations.AddField(
            model_name='menu',
            name='subItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.addition'),
        ),
    ]
