# Generated by Django 4.1.7 on 2023-02-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_people',
        ),
        migrations.RemoveField(
            model_name='category',
            name='for_whom_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type_category',
        ),
        migrations.DeleteModel(
            name='CategoryPeople',
        ),
        migrations.DeleteModel(
            name='ForWhomCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='type_category',
            field=models.ManyToManyField(related_name='product_type_category', to='product.typecategory'),
        ),
    ]
