# Generated by Django 4.1.7 on 2023-02-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_category_category_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutproduct',
            name='included',
        ),
        migrations.RemoveField(
            model_name='aboutproduct',
            name='key_features',
        ),
        migrations.AddField(
            model_name='aboutproduct',
            name='included',
            field=models.ManyToManyField(to='product.whatsincluded'),
        ),
        migrations.AddField(
            model_name='aboutproduct',
            name='key_features',
            field=models.ManyToManyField(to='product.keyfeatures'),
        ),
    ]
