# Generated by Django 4.1.7 on 2023-02-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_aboutproduct_included_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproduct',
            name='included',
            field=models.ManyToManyField(blank=True, to='product.whatsincluded'),
        ),
        migrations.AlterField(
            model_name='aboutproduct',
            name='key_features',
            field=models.ManyToManyField(blank=True, to='product.keyfeatures'),
        ),
    ]
