# Generated by Django 4.1.7 on 2023-02-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_color_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuecharacter',
            name='key_features',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.namecharacter'),
        ),
    ]
