# Generated by Django 4.1.7 on 2023-02-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_offer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='inside_photo',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.DeleteModel(
            name='ServiceCenter',
        ),
        migrations.DeleteModel(
            name='StorePoints',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='MediaBlog',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='OfferCategory',
        ),
    ]
