# Generated by Django 4.1.7 on 2023-03-01 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_blogpost_inside_photo_remove_offer_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type_tire',
        ),
        migrations.AddField(
            model_name='category',
            name='feature',
            field=models.ManyToManyField(null=True, to='product.keyfeatures'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.ManyToManyField(related_name='product_type_category', to='product.forwhomcategory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='catalog_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.technologycategory'),
        ),
    ]
