# Generated by Django 4.1.7 on 2023-03-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_titleproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategory',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.titleproduct'),
        ),
    ]
