# Generated by Django 4.1.7 on 2023-03-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_catalogcategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tech_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.titleproduct'),
        ),
    ]
