# Generated by Django 4.1.7 on 2023-03-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_category_tech_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategory',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.typecategory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tech_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.typecategory'),
        ),
        migrations.DeleteModel(
            name='TitleProduct',
        ),
    ]
