from django.contrib import admin

from product.models import *

admin.site.register(EquipmentCategory)
admin.site.register(TypeTireCategory)
admin.site.register(GuaranteeCategory)
admin.site.register(AdditionalServicesCategory)
admin.site.register(GiftWrappingCategory)
admin.site.register(TechniqueCategory)
admin.site.register(TypeCategory)
admin.site.register(Category)
admin.site.register(WhatsIncluded)
admin.site.register(KeyFeatures)
admin.site.register(AboutProduct)
admin.site.register(NameCharacter)
admin.site.register(ValueCharacter)
admin.site.register(Media)
admin.site.register(PaymentCategory)
admin.site.register(DeliveryCategory)
admin.site.register(DeliveryPayment)
admin.site.register(Warranty)
admin.site.register(VersionMax)
admin.site.register(Comment)
admin.site.register(Product)
admin.site.register(Color)
admin.site.register(Menu)
admin.site.register(Status)
admin.site.register(Banner)
admin.site.register(PlaceCategory)
admin.site.register(MediaBanner)